from core.config.banner import BannerConfig

BANNER_CONFIGS = {
    "Star Rail": {
        "standard": BannerConfig(
            game_name="Star Rail",
            banner_type="Standard",
            base_rate=0.006,
            four_star_rate=0.051,
            soft_pity_start_after=73,
            hard_pity=90,
            rate_increase=0.07,
            guaranteed_rate_up=False,
            rate_up_chance=0.5,
        ),
        "limited": BannerConfig(
            game_name="Star Rail",
            banner_type="Limited",
            base_rate=0.006,
            four_star_rate=0.051,
            soft_pity_start_after=73,
            hard_pity=90,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=0.5,
        ),
        "light_cone": BannerConfig(
            game_name="Star Rail",
            banner_type="Light Cone",
            base_rate=0.008,
            four_star_rate=0.066,
            soft_pity_start_after=65,
            hard_pity=80,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=0.75,
        ),
    },
    "Genshin Impact": {
        "standard": BannerConfig(
            game_name="Genshin Impact",
            banner_type="Standard",
            base_rate=0.006,
            four_star_rate=0.051,
            soft_pity_start_after=73,
            hard_pity=90,
            rate_increase=0.07,
            guaranteed_rate_up=False,
            rate_up_chance=0.5,
        ),
        "limited": BannerConfig(
            game_name="Genshin Impact",
            banner_type="Limited",
            base_rate=0.006,
            four_star_rate=0.051,
            soft_pity_start_after=73,
            hard_pity=90,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=0.5,
        ),
        "weapon": BannerConfig(
            game_name="Genshin Impact",
            banner_type="Weapon",
            base_rate=0.007,
            four_star_rate=0.066,
            soft_pity_start_after=62,
            hard_pity=80,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=0.75,
        ),
    },
    "Zenless Zone Zero": {
        "standard": BannerConfig(
            game_name="Zenless Zone Zero",
            banner_type="Standard",
            base_rate=0.006,
            four_star_rate=0.051,
            soft_pity_start_after=73,
            hard_pity=90,
            rate_increase=0.07,
            guaranteed_rate_up=False,
            rate_up_chance=0.5,
        ),
        "limited": BannerConfig(
            game_name="Zenless Zone Zero",
            banner_type="Limited",
            base_rate=0.006,
            four_star_rate=0.051,
            soft_pity_start_after=73,
            hard_pity=90,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=0.5,
        ),
        "w_engine": BannerConfig(
            game_name="Zenless Zone Zero",
            banner_type="W-Engine",
            base_rate=0.01,
            four_star_rate=0.08,
            soft_pity_start_after=64,
            hard_pity=80,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=0.75,
        ),
        "bangboo": BannerConfig(
            game_name="Zenless Zone Zero",
            banner_type="Bangboo",
            base_rate=0.01,
            four_star_rate=0.051,
            soft_pity_start_after=64,
            hard_pity=80,
            rate_increase=0.07,
            guaranteed_rate_up=True,
            rate_up_chance=1.0,
        ),
    },
}
