# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@testing-library/*"
          - "eslint*"
          - "typescript*"
          - "vitest*"
      vue:
        patterns:
          - "vue*"
          - "@vue/*"
          - "@vitejs/*"
      tailwind:
        patterns:
          - "tailwindcss*"
          - "@tailwindcss/*"

  - package-ecosystem: "pip"
    directory: "/stats"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      data-science:
        patterns:
          - "seaborn"
          - "ruff"
