linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - bodyclose
    - gocritic
    - godot
    - gofumpt
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: receiver-naming
        severity: warning
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]
  gofumpt:
    extra-rules: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - hugeParam
  godot:
    scope: declarations
    capital: true

run:
  go: "1.21"
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - embedded/dist
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    - path: internal/web/embedded/
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 